### ISSUE TITLE
What is the tool to flash the OpenBMC build image into a BMC on Intel S2600GZ Motherboard 

### ISSUE THREAD

**Issue by shubhabrata1979** [openbmc/obmc-console#19]
Hello,
I have built an openBMC image for Intel S2600GZ Board, want to flash it on the BMC chip. I am new to OpenBMC, is it documented somewhere about how to access the BMC console and boot with this image. The following are the methods which I tried but not getting access:
1) Serial - USB Console - not successful due to some cable/port issues.
2) Dediprog Cable - Unable to connect because there are no connector pins present for getting the debug console.
What are the other alternatives do I have ?? 
Kindly assist if there are any.
Thanks,

**Comment by williamspatrick** [comment]
Please send this question to the mailing list.  You're not going to get much support by opening issues on unrelated code repositories.
