### ISSUE TITLE
Provide mirroring to a local UART

### ISSUE THREAD

**Issue by jk-ozlabs** [openbmc/obmc-console#3]
We'd like to mirror the VUART (as accessed by `obmc-console-server`) to a local BMC UART device, like a suitable `/dev/ttySn`.

This would just be a new handler type, outputting data to the serial device.

However, we'll need to be careful of flow-control issues. We'll be outputting to a serial port with a slower baud rate than the VUART (which has no baud rate restriction, and can run at up to the speed of the LPC clock), so writes to the local UART may slow all UART processing, unless we have a suitable buffer, including possible overrun handling.

**Comment by jk-ozlabs** [comment]
Should be fixed by https://github.com/openbmc/obmc-console/commit/bc1e893375e4887ef7676c5738779c4a2f5b1935

**Comment by anoo1** [comment]
Available in openbmc v0.8 tag.
